version: '3'
services:

    auth_service:
        image: node:alpine
        volumes:
            - .:/usr/src/app
        working_dir: /usr/src/app
        ports:
            - 4001:4001
        environment:
            - MONGO_URI=mongodb+srv://nuttapong:CKdUsElZwNwiXDBu@cluster0.dtkhjsn.mongodb.net/?retryWrites=true&w=majority
            - AUTH_PORT=4001
            - TOKEN_KEY = secretofsecretsecretofsecret
        command: ['/bin/sh', '-c', 'yarn install && yarn dev-auth']
    
    showtime_service:
        image: node:alpine
        volumes:
            - .:/usr/src/app
        working_dir: /usr/src/app
        ports:
            - 4002:4002
        environment:
            - MONGO_URI=mongodb+srv://nuttapong:CKdUsElZwNwiXDBu@cluster0.dtkhjsn.mongodb.net/?retryWrites=true&w=majority
            - SHOWTIME_PORT=4002
        command: ['/bin/sh', '-c', 'yarn install && yarn dev-showtime']

    entity_service:
        image: node:alpine
        volumes:
            - .:/usr/src/app
        working_dir: /usr/src/app
        ports:
            - 4003:4003
        environment:
            - MONGO_URI=mongodb+srv://nuttapong:CKdUsElZwNwiXDBu@cluster0.dtkhjsn.mongodb.net/?retryWrites=true&w=majority
            - ENTITY_PORT = 4003
        command: ['/bin/sh', '-c', 'yarn install && yarn dev-entity']
        
    booking_service:
        image: node:alpine
        volumes:
            - .:/usr/src/app
        working_dir: /usr/src/app
        ports:
            - 4004:4004
        environment:
            - MONGO_URI=mongodb+srv://nuttapong:CKdUsElZwNwiXDBu@cluster0.dtkhjsn.mongodb.net/?retryWrites=true&w=majority
            - BOOKING_PORT = 4004
        command: ['/bin/sh', '-c', 'yarn install && yarn dev-booking']

    api_service:
        image: node:alpine
        volumes:
            - .:/usr/src/app
        working_dir: /usr/src/app
        ports:
            - 8080:8080
        environment:
            - API_PORT=8080
        command: ['/bin/sh', '-c', 'yarn install && yarn dev-api']
    
networks:
    microservicenetwork:
        external: true
